### ISSUE TITLE
Ota auto update

### ISSUE THREAD

**Issue by grzegorzlabudda** [romasku/tuya-zigbee-switch#20]
Hello
is it possible to automatically update ota without re-uploading files to the ha server? the idea is for z2m to know that there is an update without going to github and downloading new files.

**Comment by romasku** [comment]
Hi,

Good point. I've discovered that it is possible to use links inside z2m's `configuration.yaml` :

```yaml
ota:
  zigbee_ota_override_index_location: >-
    https://raw.githubusercontent.com/romasku/tuya-zigbee-switch/refs/heads/main/zigbee2mqtt/ota/index_router.json
```

Also, I've updated the docs to include this method. 

It still may require downloading a new converter if it was updated, but it should happen rarely.
