### ISSUE TITLE
ZHA OTA documentation fix

### ISSUE THREAD

**Issue by soosp** [romasku/tuya-zigbee-switch#62]
Hi,

At first a big thank you for this awesome project. I was able successfully update my AVATTO LZWSM16-2 switch, but the current ZHA release I had to use different configuration:
```
zha:
  enable_quirks: true
  custom_quirks_path: /config/custom_zha_quirks
  zigpy_config:
    ota:
      enabled: true
      extra_providers:
        - type: z2m
          url: https://raw.githubusercontent.com/romasku/tuya-zigbee-switch/refs/heads/main/zigbee2mqtt/ota/index_router.json
```

The first two lines needed for quirks. I had to copy your quirk to this directory. It is only necessary after update, for use the custom firmware.
The `zigpy_config` part was needed for the OTA. After modify the `configuration.yaml` you have to restart Home Assistant. After restart the at Configuration, System, Updates I was able to trigger the update check by clicking on the round arrow. It rescans the updates for the system.
The OTA update appeared soon. After update I had to remove the device from ZHA, restart the Home Assistant, pair again the switch. It works well with your quirk.

**Comment by soosp** [comment]
Meanwhile an AVATTO ZWSM16-2 switch was updated successfully with this method.

**Comment by soosp** [comment]
Additional information about triggering the OTA update (source: [https://community.home-assistant.io/t/force-zha-device-update/800436/4](url):

Go to Developer tools -> Actions, then switch to YAML mode
```
action: zha.issue_zigbee_cluster_command
data:
  ieee: <INSERT IEEE OF DEVICE HERE>
  endpoint_id: 1
  cluster_type: out
  command_type: client
  cluster_id: 25
  command: 0
  args:
    - 0
    - 100
```
This way I was able to force to trigger to find the update for a new device.
